#!/usr/bin/bash
# Tested only for Debian
# EDIT THE `codename` BELOW ! ! !

codename="trixie"

append(){ # $1: text, $2: path
    sudo=""
    if [[ $2 != */home* ]]; then
        sudo="sudo"
    fi

    $sudo mkdir -p $(dirname "$2") && $sudo touch "$2"
    if [[ $(cat $2) == *"$1"* ]]; then
        echo -e "
        \rThe following lines were already added
        \r=============
        \r$1
        \r============="
    else
        cat << POMU | $sudo tee -a $2 > /dev/null
        $1
POMU
    fi
}

sudo apt update -y
sudo apt upgrade -y

# Remove LibreOffice
#echo "
#Removing LibreOffice"
#sudo apt-get remove --purge libreoffice*
#sudo apt-get clean
#sudo apt-get autoremove

# apt
echo "
Installing apt packages"
sudo apt install -t $codename-backports yt-dlp streamlink -y
sudo apt install flatpak systemd-timesyncd gnome-software-plugin-flatpak mpv qbittorrent kdenlive mkvtoolnix-gui git wget xclip fastfetch aria2 qt5ct -y

# flatpak
echo "
Installing flatpak packages"
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.belmoussaoui.Authenticator com.discordapp.Discord com.getpostman.Postman com.github.finefindus.eyedropper com.mattjakeman.ExtensionManager org.kde.krita org.localsend.localsend_app -y

# Github CLI & login
echo "
Installing Github CLI & login"
(type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y

gh auth login

# Linux config
echo "
Adding Linux configs"
git clone https://github.com/pomubry/linux-config.git ~/Downloads/linux-config
chmod +x ~/Downloads/linux-config/bin/*
mkdir ~/bin
cp -r ~/Downloads/linux-config/bin ~/Downloads/linux-config/mumble-dark.qbtheme ~/Downloads/linux-config/.poshthemes ~/Downloads/linux-config/.editorconfig ~
cp -r ~/Downloads/linux-config/Code ~/Downloads/linux-config/mpv ~/.config

append '
# bin
export PATH=~/bin:$PATH
export QT_QPA_PLATFORMTHEME=qt5ct' ~/.bashrc

if [[ $(cat ~/.gitconfig) == *defaultbranch* ]]; then
    echo -e "\nGithub user/defaultbranch config already added. Skipping..."
else
    echo "$(cat ~/Downloads/linux-config/.gitconfig)
$(cat ~/.gitconfig)" >> ~/.gitconfig
fi

rm -rf ~/Downloads/linux-config

# oh-my-posh
echo "
Installing oh-my-posh"
append '
# oh-my-posh
export PATH=$PATH:/root/.local/bin' ~/.bashrc
curl -s https://ohmyposh.dev/install.sh | bash -s
chmod u+rw ~/.poshthemes/*.omp.*

# font for oh-my-posh
echo "
Installing font for oh-my-posh"
oh-my-posh font install jetbrainsmono

# config for oh-my-posh
append '
# poshtheme config
eval "$(oh-my-posh init bash --config ~/.poshthemes/pdrome.omp.json)"' ~/.bashrc

# nvm
echo "
Installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

# VSCode
wget "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" -O ~/Downloads/vscode.deb
sudo apt install ~/Downloads/vscode.deb
echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections
rm ~/Downloads/vscode.deb

# Veracrypt
echo "
Installing Veracrypt"
veracryptLatest=$(curl https://veracrypt.io/en/Downloads.html | grep -i "Latest Stable Release" | egrep -o "[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}")
debianVersion=$(lsb_release -d | egrep -o "[0-9]{2}")
veracryptGui="https://launchpad.net/veracrypt/trunk/$veracryptLatest/+download/veracrypt-$veracryptLatest-Debian-$debianVersion-amd64.deb"
wget $veracryptGui -O ~/Downloads/veracryptGui.deb
sudo apt install ~/Downloads/veracryptGui.deb -y
rm ~/Downloads/veracryptGui.deb

# ProtonVPN
echo "
Installing ProtonVPN"
protonvpn=$(curl https://protonvpn.com/support/official-linux-vpn-debian/ | grep "/stable" | egrep -o "https.+\.deb")
wget $protonvpn -O ~/Downloads/protonvpn.deb
sudo apt install ~/Downloads/protonvpn.deb

echo "Add a custom source list because the package seems to be broken. Check the official instruction first."
echo "
Types: deb
URIs: https://repo.protonvpn.com/debian
Suites: stable
Components: main
Signed-By: /usr/share/keyrings/protonvpn-stable-archive-keyring.gpg

target ===> /etc/apt/sources.list.d/protonvpn-stable.sources"
read

sudo apt update -y
sudo apt install proton-vpn-gnome-desktop
sudo apt install libayatana-appindicator3-1 gir1.2-ayatanaappindicator3-0.1 gnome-shell-extension-appindicator
rm ~/Downloads/protonvpn.deb

# .NET
# source: https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian
#wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
#sudo dpkg -i packages-microsoft-prod.deb
#rm packages-microsoft-prod.deb

#sudo apt-get update && \
#  sudo apt-get install -y dotnet-sdk-8.0

echo "Done!"
