#!/usr/bin/env zsh
# Tested for MacOS only

append() { # $1: text, $2: path
  sudo=""
  if [[ $2 != */home* ]]; then
    sudo="sudo"
  fi

  $sudo mkdir -p "$(dirname "$2")" && $sudo touch "$2"
  if [[ $(cat "$2") == *"$1"* ]]; then
    echo -e "
        \rThe following lines were already added
        \r=============
        \r$1
        \r============="
  else
    cat <<POMU | $sudo tee -a "$2" >/dev/null
        $1
POMU
  fi
}

# Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo >> ~/.zshrc
echo >> /Users/pdrome/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv zsh)"' >> /Users/pdrome/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv zsh)"  

source ~/.zshrc

brew install aldente git gh yt-dlp xclip fastfetch starship aria2 lux \
  neovim lazygit fzf ripgrep fd

brew install --cask keyboardcleantool iina middleclick alt-tab quicklook-video iloader stats flowvision hiddenbar firefox@esr libreoffice localsend bitwarden qbittorrent veracrypt-fuse-t discord mkvtoolnix-app visual-studio-code docker-desktop postman pika protonvpn


# Starship
mkdir ~/.config
curl -LO https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
tar -C ~/Library/Fonts -xzf JetBrainsMono.tar.xz JetBrainsMonoNerdFont-Regular.ttf
echo 'eval "$(starship init zsh)"' >>~/.zshrc
source ~/.zshrc
starship preset catppuccin-powerline -o ~/.config/starship.toml

# Github Login & CLI
gh auth login

# nvm
echo "
Installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

source ~/.zshrc
nvm install --lts

# Linux config
echo "
Adding Linux configs"
git clone https://github.com/pomubry/linux-config.git ~/Downloads/linux-config
chmod +x ~/Downloads/linux-config/bin/*
mkdir ~/bin
cp -r ~/Downloads/linux-config/bin ~/Downloads/linux-config/.editorconfig ~
cp -r ~/Downloads/linux-config/config/. ~/.config
cp -r ~/Downloads/linux-config/browser ~/Downloads

echo >> ~/.gitconfig
if [[ -f ~/.gitconfig && $(cat ~/.gitconfig) == *defaultbranch* ]]; then
  echo -e "\nGithub user/defaultbranch config already added. Skipping..."
else
  echo "$(cat ~/Downloads/linux-config/.gitconfig)
$(cat ~/.gitconfig)" > ~/.gitconfig
fi

rm -rf ~/Downloads/linux-config

# LazyVim
git clone https://github.com/pomubry/lazyvim.git ~/.config/nvim

append '
gui:
  theme:
    selectedLineBgColor:
      - "#313244"' ~/Library/Application\ Support/lazygit/config.yml

append "
# neovim
export EDITOR=nvim
source <(fzf --zsh)" ~/.zshrc
mkdir ~/.local/bin
ln -s "$(which fdfind)" ~/.local/bin/fd

append "
# bin
export PATH=~/bin:\$PATH
WORDCHARS='*?_-[]~=&;!#$%^(){}<>'" ~/.zshrc

append $'
# alias
alias lsg=\'ls -G\'
alias dus=\'du -sh -- ./* | sort -h\'
alias dusd=\'du -sh -- ./*/ | sort -h\'
alias cdpwd=\'cd $(pwd)\'
alias cddev="cd /Volumes/vc/backup/linux/Documents/dev/"' ~/.zshrc

echo "
TODO: 
iina > advanced > load-scripts=yes
ghostty > theme = Catppuccin Mocha
screen lock > ask for password immediately
menu bar > show battery percentage
display > when connected to tv > mirror entire screen
desktop and dock > disable lower right corner shortcut
sound > play feedback when volume changed
keyboard shortcut > services > 'new terminal tab at folder'
keyboard autocorrect
trackpad > app expose"

echo "Done!"
